### PR TITLE
Visual for Friends list

### PR DESCRIPTION
**Pull request by DigiLeaf**
This is just updating the visuals for the friends list page. It still needs a home button but for now you can just use the web browser back arrow.

This addresses issue #33

### CODE REVIEW

**Review by kwo20 — CHANGES_REQUESTED** [review]
The file system is incorrect, you have two folders with the entire app in it, as well as some extra files that don't. You have to fix the branch before we can push this to main.

**Review by hb1078 — CHANGES_REQUESTED** [review]
Same as what Keith said, when you get your branch looking like the main branch, you can put your changes into your branch, and then submit the pull request.

**Comment by DigiLeaf** [comment]
Can this please be reviewed again? I believe I have sorted out the issues. It still needs a home button, but this should be done otherwise.

**Review by kwo20 — COMMENTED** [review]
The findfriends.css is not in the correct folder, it should be in the static folder.

**Comment by DigiLeaf** [comment]
I don't know why it was not. But I fixed it, that should finally be correct.

**Review by kwo20 — APPROVED** [review]
Thanks for fixing it all, looks good now!

**Review by hb1078 — APPROVED** [review]
Looks good to me as well.

**Pull request merged**
