### PR TITLE
Adding the functionality for the posts/timeline

### PR DESCRIPTION
**Pull request by kwo20**
References Issue #23 
Updates app.py and the database.
A user can make posts and view the posts on their timeline now.

### CODE REVIEW

**Review by darcie76 — APPROVED** [review]
Plz fix the conflicts before merging but otherwise 👍

**Comment by hb1078** [comment]
Looks good, the conflicts that need to be resolved can easily be fixed.

**Review by DigiLeaf — APPROVED** [review]
These look fine. The conflicts look fairly straightforward to solve

**Review by hb1078 — APPROVED** [review]

**Comment by kwo20** [comment]
Resolved the conflicts on the two CSS pages.

**Pull request merged**
