### PR TITLE
Pull config for CircleCI and basic tests

### PR DESCRIPTION
**Pull request by kwo20**
References Issue #38

### CODE REVIEW

**Review by hb1078 — APPROVED** [review]
Looks good to me.

**Review by DigiLeaf — APPROVED** [review]
Looks fine

**Review by darcie76 — APPROVED** [review]
looks good :)

**Comment by kwo20** [comment]
Had an issue with the database with this Pull Request, used Github Desktop to fix it. That is why the pull request was not merged at the end.

**Pull request closed without merging**
